# Generated by Django 5.2.8 on 2025-11-30 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DryingRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('installation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_type', models.CharField(choices=[('rain', 'Chuva'), ('smoke', 'Fumo'), ('error', 'Erro'), ('manual', 'Manual')], max_length=20)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('drying_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='estendal.dryingrack')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('rain', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('drying_time_estimate', models.IntegerField(blank=True, null=True)),
                ('clothesline_state', models.CharField(choices=[('extended', 'Estendido'), ('retracted', 'Recolhido')], default='extended', max_length=20)),
                ('drying_rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='estendal.dryingrack')),
            ],
        ),
        migrations.AddField(
            model_name='dryingrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_racks', to='estendal.user'),
        ),
    ]
