# Generated by Django 5.2.8 on 2025-12-03 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryingrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drying_racks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='smoke',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('rain', 'Chuva'), ('error', 'Erro'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
