# Generated by Django 5.2.8 on 2025-12-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0002_alter_dryingrack_user_remove_sensor_smoke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dryingrack',
            name='pairing_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='dryingrack',
            name='serial_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
