# Generated by Django 5.2.8 on 2025-12-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0003_dryingrack_pairing_code_dryingrack_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='clothesline_state',
        ),
        migrations.AddField(
            model_name='dryingrack',
            name='clothesline_state',
            field=models.CharField(choices=[('extended', 'Estendido'), ('retracted', 'Recolhido')], default='retracted', max_length=20),
        ),
    ]
