# Generated by Django 5.2.8 on 2025-12-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0004_remove_sensor_clothesline_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dryingrack',
            name='clothesline_state',
        ),
        migrations.AddField(
            model_name='sensor',
            name='clothesline_state',
            field=models.CharField(choices=[('extended', 'Estendido'), ('retracted', 'Recolhido')], default='extended', max_length=20),
        ),
    ]
