# Generated by Django 5.2.8 on 2025-12-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0005_remove_dryingrack_clothesline_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='sensor',
            name='light_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
