# Generated by Django 5.2.8 on 2025-12-22 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0006_remove_sensor_wind_speed_sensor_light_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryingrack',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dryingrack',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dryingrack',
            name='pairing_code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='dryingrack',
            name='serial_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='dryingrack',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drying_racks', to=settings.AUTH_USER_MODEL),
        ),
    ]
