# Generated by Django 5.2.8 on 2025-12-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0007_alter_dryingrack_active_alter_dryingrack_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='clothesline_state',
            field=models.CharField(choices=[('extended', 'Estendido'), ('retracted', 'Recolhido')], default='retracted', max_length=20),
        ),
    ]
