# Generated by Django 5.2.8 on 2025-12-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0008_alter_sensor_clothesline_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='clothesline_state',
        ),
        migrations.AddField(
            model_name='dryingrack',
            name='clothesline_state',
            field=models.CharField(choices=[('extended', 'Aberto'), ('retracted', 'Fechado')], default='retracted', max_length=20),
        ),
    ]
