# Generated by Django 5.2.8 on 2025-12-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0009_remove_sensor_clothesline_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dryingrack',
            name='manual_command',
            field=models.CharField(blank=True, choices=[('open', 'Abrir'), ('close', 'Fechar')], max_length=10, null=True),
        ),
    ]
