# Generated by Django 5.2.8 on 2025-12-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estendal', '0010_dryingrack_manual_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dryingrack',
            name='manual_command',
        ),
    ]
